{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8a2d27ef-fb2d-459e-bb17-adc133c4e4f5",
   "metadata": {},
   "outputs": [],
   "source": [
    "# program 2\n",
    "\"\"\"Roll a six-sided die 6,000 times.\"\"\"\n",
    "import random\n",
    "\n",
    "# face frequency counters\n",
    "frequency1 = 0\n",
    "frequency2 = 0\n",
    "frequency3 = 0\n",
    "frequency4 = 0\n",
    "frequency5 = 0\n",
    "frequency6 = 0\n",
    "frequency7 = 0\n",
    "frequency8 = 0\n",
    "frequency9 = 0\n",
    "frequency10 = 0\n",
    "frequency11 = 0\n",
    "frequency12 = 0\n",
    "\n",
    "trials = 6_000\n",
    "\n",
    "# 6,000,000 die rolls\n",
    "for roll in range(6_000): # note underscore separators\n",
    "    face = random.randrange(1, 7) + random.randrange(1,7)\n",
    "    \n",
    "    #increment appropriate face counter\n",
    "    if face == 1:\n",
    "        frequency1+= 1\n",
    "    if face == 2:\n",
    "        frequency2+= 1\n",
    "    if face == 3:\n",
    "        frequency3+= 1\n",
    "    if face == 4:\n",
    "        frequency4+= 1\n",
    "    if face == 5:\n",
    "        frequency5+= 1\n",
    "    if face == 6:\n",
    "        frequency6+= 1\n",
    "    if face == 7:\n",
    "        frequency7+= 1\n",
    "    if face == 8:\n",
    "        frequency8+= 1\n",
    "    if face == 9:\n",
    "        frequency9+= 1\n",
    "    if face == 10:\n",
    "        frequency10+= 1\n",
    "    if face == 11:\n",
    "        frequency11+= 1\n",
    "    if face == 12:\n",
    "        frequency12+= 1\n",
    "        \n",
    "craps = (frequency2 + frequency3 + frequency12)\n",
    "wins = (frequency7 + frequency11)\n",
    "        \n",
    "print(f'Face{\"Frequency\":>13}')\n",
    "print(f'{1:>4}{frequency1:>13}')\n",
    "print(f'{2:>4}{frequency2:>13}')\n",
    "print(f'{3:>4}{frequency3:>13}')\n",
    "print(f'{4:>4}{frequency4:>13}')\n",
    "print(f'{5:>4}{frequency5:>13}')\n",
    "print(f'{6:>4}{frequency6:>13}')\n",
    "print(f'{7:>4}{frequency7:>13}')\n",
    "print(f'{8:>4}{frequency8:>13}')\n",
    "print(f'{9:>4}{frequency9:>13}')\n",
    "print(f'{10:>4}{frequency10:>13}')\n",
    "print(f'{11:>4}{frequency11:>13}')\n",
    "print(f'{12:>4}{frequency12:>13}')\n",
    "\n",
    "print(f'Craps =', (craps/trials))\n",
    "print(f'Wins =', (wins/trials))\n",
    "print(f'My name is Kim Leach')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
